### ISSUE TITLE
在类RuntimeStack中可能存在内存访问冲突

### ISSUE THREAD

**Issue by NaturalSelect** [theflysong/rain#1]
https://github.com/theflysong/rain/blob/bdf058e36c9ee5bfa565c0385441977f6c1aad3d/RVM/SCIRuntimeStack.cpp#L24
在`SCIRuntimeStack.h`中的`void push(Value value)`将Value进行值传递(这将导致值拷贝)，而类`Value`在析构函数中释放了内存这将导致储存在`RuntimeStack::statck`中的Value储存一个无效的地址

**Comment by NaturalSelect** [comment]
现在发现在其他代码中也存在这个问题

**Comment by theflysong** [comment]
这个我也在是试图进行修改
也没发现什么好的方法。
希望大佬指点一条活路

**Comment by theflysong** [comment]
目前是准备使用指针来存了

**Comment by NaturalSelect** [comment]
3个方案:
1.移动语义
2.引用计算
3.shared_ptr

**Comment by NaturalSelect** [comment]
如果方便还是留个QQ吧，在这里聊挺麻烦的

**Comment by theflysong** [comment]
QQ:2715626245

**Comment by theflysong** [comment]
已修改
