### ISSUE TITLE
函数'print'应该返回一个Value却并未返回任何值,这可能导致未定义行为

### ISSUE THREAD

**Issue by NaturalSelect** [theflysong/rain#2]
https://github.com/theflysong/rain/blob/bdf058e36c9ee5bfa565c0385441977f6c1aad3d/RVM/CFBasicIO.cpp#L3
C++文档: https://zh.cppreference.com/w/cpp/language/return

**Comment by NaturalSelect** [comment]
https://github.com/theflysong/rain/blob/master/RVM/CFBasicIO.cpp#L3

**Comment by theflysong** [comment]
已解决
