### ISSUE TITLE
Value::setStr不该接受一个int作为参数

### ISSUE THREAD

**Issue by NaturalSelect** [theflysong/rain#6]
https://github.com/theflysong/rain/blob/bdf058e36c9ee5bfa565c0385441977f6c1aad3d/RVM/Value.cpp#L43
`std::string::operator=`并没有以int为参数的重载函数,但有可能使用`std::string::operator=(char)`这可能导致意想不到的结果
C++文档: https://zh.cppreference.com/w/cpp/string/basic_string/operator%3D

**Comment by NaturalSelect** [comment]
https://github.com/theflysong/rain/blob/bdf058e36c9ee5bfa565c0385441977f6c1aad3d/RVM/Value.cpp#L73
在这里也有这个问题

**Comment by theflysong** [comment]
我知道了
还没写完QAQ
连半成品都不算

**Comment by theflysong** [comment]
已修改
